### PR TITLE
Fixed compile time errors

### PR DESCRIPTION
**Pull request by speqtr**
- fixed global compiler settings in cmake scripts;
- fixed QwertycoinFramework includes;

### CODE REVIEW

**Comment by speqtr** [comment]
**NOTE:** First iteration of updates will fail due to broken Qt5 dir path on AppVeyor CI, because they updated Qt5 paths on there CI machines. I'll push one extra commit to fix it.

**Comment by speqtr** [comment]
Latest commit should fix issues with Qt5 paths on AppVeyor CI.

**Comment by nnian** [comment]
@speqtr can this merged too?

**Comment by speqtr** [comment]
Yes 👍

**Pull request merged**
